# Generated by Django 5.2.8 on 2025-11-13 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('LA_SANTA', 'La Santa'), ('LA_RIFA', 'La Rifa'), ('EL_SORTEO', 'El Sorteo')], max_length=50)),
                ('factor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sorteos_diarios', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_ganador', models.IntegerField()),
                ('numero_sorteo_dia', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sorteo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apostado', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('numero_sorteo_dia', models.IntegerField()),
                ('es_ganador', models.BooleanField(default=False)),
                ('premio_pagado', models.BooleanField(default=False)),
                ('fecha_pago_premio', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sorteo')),
            ],
        ),
        migrations.CreateModel(
            name='RecaudacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_recaudado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_premios', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sorteo')),
            ],
            options={
                'unique_together': {('fecha', 'sorteo')},
            },
        ),
    ]
